/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 1.3.40
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package edu.cmu.pocketsphinx;

public class Prob {
  private long swigCPtr;
  protected boolean swigCMemOwn;

  protected Prob(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(Prob obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        pocketsphinxJNI.delete_Prob(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public void setUttid(String value) {
    pocketsphinxJNI.Prob_uttid_set(swigCPtr, this, value);
  }

  public String getUttid() {
    return pocketsphinxJNI.Prob_uttid_get(swigCPtr, this);
  }

  public void setProb(int value) {
    pocketsphinxJNI.Prob_prob_set(swigCPtr, this, value);
  }

  public int getProb() {
    return pocketsphinxJNI.Prob_prob_get(swigCPtr, this);
  }

  public Prob(String uttid, int prob) {
    this(pocketsphinxJNI.new_Prob(uttid, prob), true);
  }

}
